### ISSUE TITLE
[ERROR] dagger::client - timeout syncing with peer

### ISSUE THREAD

**Issue by StoneMac65** [GenesysGo/dagger-testnet-issues#13]
My node stopped syncing after 24 hours of running with no issues. I share the logs for the pas 24 hours, hopefully it helps to find the root cause
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13852155/config.zip)

**Comment by StoneMac65** [comment]
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13852154/config.zip)

**Comment by tracy-codes** [comment]
Closing as a duplicate of #4
