### ISSUE TITLE
VPS is shutdown/aported 

### ISSUE THREAD

**Issue by rsamban** [GenesysGo/dagger-testnet-issues#16]
**Describe the bug**
My node had been running good for a day and I noticed that my server is shutdown. wield is the only process that I am running in it. After server restart, I am noticing some control characters in config.log. I have attached my config.log (my node is running fine after restart and this is the first time this has happened)

[config.log_20240108.tgz](https://github.com/GenesysGo/dagger-testnet-issues/files/13868730/config.log_20240108.tgz)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rsamban** [comment]
It happened again today after 3 hours of run

**Comment by tracy-codes** [comment]
This is likely an issue with your host provider. I'd suggest reaching out to them for further support for this issue.
