### ISSUE TITLE
Too Many Files Open - Revisited in 0.7.4

### ISSUE THREAD

**Issue by g-scooter** [GenesysGo/dagger-testnet-issues#17]
**Describe the bug**
After downloading 0.7.4, uninstall then reinstall... I'm getting the Too Many Files Open error again (see previous issue #9)

**To Reproduce**
Run wield node.

**Additional context**
I'm running on Contabo.

![2024-01-16 06_30_38-Window](https://github.com/GenesysGo/dagger-testnet-issues/assets/99210276/d9ab2eb0-ac56-4313-8136-39b9ede8a333)

**Comment by g-scooter** [comment]
Rebooted server.  Seemed to run again, without error, for about 10 minutes, then Too many open files error. Still finalizing.

**Comment by tracy-codes** [comment]
This specific instance of the `TooManyFiles` error is resolved as of a recent version release.
