### ISSUE TITLE
UI error.

### ISSUE THREAD

**Issue by crypt0miester** [GenesysGo/dagger-testnet-issues#2]
**Describe the bug**
Cannot view transaction due to an "Expected Uint8Array" from the Chrome DevTools.

**To Reproduce**
1. Go to [dagger-hammer](https://dagger-hammer.shadow.cloud/)
2. Click on Start Game, type Anything.
3. Click on the Green Confirmed Transaction
4. Click on View event details
5. Application error: a client-side exception has occurred (see the browser console for more information).
[Sample URL](https://dagger-hammer.shadow.cloud/explorer/event/4yiSq5VPHYrp5vPUDrkd3FvrLXDuUuvqLxBaapJgca6QPg6rDPUCWgQHwvHNgnHQUvYj4h179w5vfp8nwfwCqCXz) 

**Expected behavior**
I excpet to see an explorer with the transaction

**Screenshots**
![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/77497858/25041b24-36ad-45a0-b819-c0e37cd9d73d)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Chrome
 - Version: 117.0.5938.132 (Official Build) (64-bit)

**Comment by tracy-codes** [comment]
Thank you for the report. This is just an issue with the client side not handling certain responses. We've taken note and will follow up once it's resolved.

**Comment by tracy-codes** [comment]
This has been resolved!
