### ISSUE TITLE
cNFT is not received in the wallet after discord verification

### ISSUE THREAD

**Issue by rsamban** [GenesysGo/dagger-testnet-issues#20]
**Describe the bug**
cNFT is not received in my wallet after discord verification.
<img width="762" alt="image" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/8595347/12414e06-9fa0-411f-b95c-574c07c5fa7c">

My node is running, I don't see any errors in the conflg.log and I am getting finalied! messages in the confg log.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cbijon** [comment]
same here

nodes running

wallets up & shdw in (more than 500)

not listed

no roles

**Comment by rev3r4nt** [comment]
Same here

**Comment by tracy-codes** [comment]
This can take a few minutes after verifying your node. Please also make sure the pubkey after importing matches your node's id. More information on how to properly import your node's keypair into a solana wallet can be found here: https://docs.shdwdrive.com/operate/wallet#private-key-method
