### ISSUE TITLE
v0.8.0 hongkong area bandwidth speed test issue

### ISSUE THREAD

**Issue by JiapengLi** [GenesysGo/dagger-testnet-issues#21]
![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/3773923/97e70f4d-4102-4626-b629-a21cf711e687)

What I see:
- wield is trying to access 43.239.139.213:8080 (ip by i3d.net)
- the speed result is stable

**Comment by JiapengLi** [comment]
a new server ip 203.210.4.91:8080 is seen, results is : (download speed becomes worse)
```
52 total_storage_space=316387205 cpu_model="Intel(R) Xeon(R) CPU E5-2650 v3 @ 2.30GHz" wield_version="0.8.0" node_id="xxxx" upload_network_speed=61614 download_network_speed=62764 ip_addr="192.168.251.16"
```

**Comment by rsamban** [comment]
I also have the same issue

Speed test comes up with much much higher upload and download speeds (especially upload), but wiled is detecting only 1/3 of it.
----
 upload_network_speed=78100 download_network_speed=133095
--------

Idle Latency:    18.11 ms   (jitter: 3.08ms, low: 16.75ms, high: 27.44ms)
    Download:   280.73 Mbps (data used: 269.7 MB)
                 59.46 ms   (jitter: 20.42ms, low: 14.69ms, high: 194.33ms)
      Upload:   205.89 Mbps (data used: 168.4 MB)
                 22.14 ms   (jitter: 5.53ms, low: 10.96ms, high: 106.04ms)

**Comment by tracy-codes** [comment]
This is fine. For now, the speed test is using speedtest.net to measure up/download for data collection purposes only. It has no bearing on how your node performs during the current testnet phase.
