### ISSUE TITLE
Node stopped accruing rewards

### ISSUE THREAD

**Issue by torroh333** [GenesysGo/dagger-testnet-issues#22]
**Describe the bug**
After node had successfully went online and started earning rewards the status changed to "Online & Queued for Rewards". The node hasn't been earning rewards since.

**Expected behavior**
Expected to continue to accrue rewards given the node remained online and continuously finalized bundles since joining the network.

**Screenshots**
![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/60167459/4e89bee7-052b-4471-a741-188059194253)

**Desktop**
VPS provider: Contabo
System: 16 cores | 64 GB | 500 GB (100% NVMe) | 1,000 Mbit/s
OS: Ubuntu 22.04
Location: New York

**Additional context**
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13958013/config.zip)

**Comment by tracy-codes** [comment]
Thank you for reporting! We are investigating this issue

**Comment by tracy-codes** [comment]
This has been resolved with a recent version release. Thank you for reporting.
