### ISSUE TITLE
Unable to get nodes ids recognized on dashboard or verification

### ISSUE THREAD

**Issue by jboyd122** [GenesysGo/dagger-testnet-issues#23]
**Describe the bug**
Nodes are running great. I previously built a node in a VM on my laptop for the original testnet. I decided to import that id into a rebuilt VM on another server for testing last week. everything went well. I was able to import the wallet, see the id on the old dashboard and verify that wallet/node id with my discord user. roles aligned as expected and all was good. A few days ago during what seemed to me as a cleanup process my node disappeared from the dashboard. I did not think much of it. Today I upgraded the node the second testnet2 launched as did a hundred other people, however my node still did not populate on the dashboard nor will it verify with my discord user. After banging my head against this for a couple hours I decided to build another VM and another node. This node will not validate either. Both nodes have over 100 shdw in the associated wallets and I retained 1990 shdw in my ledger with my SSC. The remaining 20k shdw is staked. Both nodes are finalizing bundles and participating on the network as expected. I'm kind of at a loss for what else to do next. I've combed through the documentation to see what step I could have possibly missed, or what silly item I did not do correctly. I even built a second VM to validate following the build docs verbatim. It's not my first round with this (I ran an RPC in Equinix with you guys back in the day) nor am I new to linux, etc. I'm really scratching my head and without positive feedback it really feels like something isn't quite right with my setup. That being said the servers do appear to be doing their job even if the front-end isn't behaving as expected. I'd appreciate a look just to validate that something isn't broken. I know you guys are super busy and getting hit from 1000 different directions so no rush. Frank said that if my nodes are doing their job then I shouldn't worry, and also the docs state that if I don't validate I don't participate which makes me hesitant. I'd be thrilled if I find that I'm just doing something dumb but at this point idk. node id's are below. Any help is appreciated.

Dnqe1y4GAgMqW9DmZNMG54JwRneb6MLWFzMJaKYTidKQ
4ut4UANtsPTSMNpQyU2bC4Ri1vC31TVms1nX6rtJvYM8

**Comment by jboyd122** [comment]
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13958708/config.zip)

**Comment by Cre8tivPrime8** [comment]
Also experiencing this: Unable to get Node ID recognized for discord verification with a previously spun up node that had been tracked before (Updated to latest version with at least 100 $SHDW in node wallet and staking wallet and finalizing in logs): 
Node ID: 6Fv9bYXVK6HgspzJye9Ptu9ZhbayGwwYHC63UzfAHRY
Staking Wallet: 9N8KBLzrnLCPckoyEoin5zmrBnKYcHUQUPy6oaJxGDgJ

**Comment by jboyd122** [comment]
I wonder if its possible there is something with nodes sitting behind a router with NAT and private IP addresses. Clearly it's not a problem to connect to the network, but if the front-end systems can't reach back and validate the server maybe it is unable to authenticate?

**Comment by cbijon** [comment]
Hi jboyd122,

I have the same setup : 2 nodes behind a router. I did nat UDP 2030 on it but if it needs something more it can be a good lead..

**Comment by tracy-codes** [comment]
> Hi jboyd122,
> 
> I have the same setup : 2 nodes behind a router. I did nat UDP 2030 on it but if it needs something more it can be a good lead..

Did you also unblock UDP 2031?

**Comment by cbijon** [comment]
yes 2031 and 2030

**Comment by cbijon** [comment]
how you take the good ip for rocksdb ?

2024-01-18T00:21:13.393192796+01:00 [INFO] dagger::db::peers - Replacing peer's addr 10.7.4.13:2030 with 78.192.232.17:22768 in rocksdb

my node should out with an another ip (83.202.152.19) , but rocksdb assign the bad ip. This is the ip of my second node. What kind of protocol are you using ? 

 All icmp, udp and tcp are routed next-hope out / masquerade with another IP normaly.

i have 2 routers interconnected with VPN.

we are ok we need 2 public  IPs  for using 2 UDP 2030 2031 ports separatly ?

**Comment by jboyd122** [comment]
I was able to telnet those ports on holders.genesysgo.com from my nodes. Are there any other network related items that might be getting in the way?

**Comment by tracy-codes** [comment]
Closing as this issue has gone stale.
