### ISSUE TITLE
holder page not showing correct balance

### ISSUE THREAD

**Issue by charles-low** [GenesysGo/dagger-testnet-issues#24]
**Describe the bug**
I have a wallet and two nodes. 
The wallet has 8000 SHDW and each node has 1000 SHDW
However in the holder portal, after adding discord verification for all three address
the balance of SHDW are still zero for both node. 

**To Reproduce**
1. Verify the private wallet and node with discord
2. transfer shdw from wallet to node 

**Expected behavior**
The holder page should show latest balance of the connected wallet and node id

**Screenshots**

**Desktop (please complete the following information):**
 - chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tracy-codes** [comment]
This has been resolved
