### ISSUE TITLE
Node missed lots of rewards

### ISSUE THREAD

**Issue by CELLI0T** [GenesysGo/dagger-testnet-issues#26]
**Describe the bug**
Node is online since the of testnet2, was accruing rewards but looks like it stopped accruing for some time, and the Uptime disappeared.

**Expected behavior**
Expected to continue to accrue rewards given the node remained online and continuously finalized bundles since joining the network.

**Screenshots**
![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/128509765/07111563-3828-4674-8e47-80ea11eb0840)

**Additional context**
[config.log.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13960339/config.log.zip)

**Comment by tracy-codes** [comment]
This has been resolved.
