### ISSUE TITLE
Discord verification not properly updating node account, duplicate node UI, duplicate cNFTs minted

### ISSUE THREAD

**Issue by warlyware** [GenesysGo/dagger-testnet-issues#28]
Today at the time of the 0.8.0 release I updated and restarted all of my nodes for the start of Testnet Phase 2. All nodes had already gone through discord verification and connected to my account profile at holders.genesysgo.com. After all three had been updated and restarted, I noticed that only 2 of them were being displayed on the leaderboard. After some investigation I then noticed that while my node's account was indeed connected to my discord profile, the node's "last updated" field was more than 3 hours behind all my other connected wallets which appeared to be getting normal, regular updates. At this point I [reported the issue in Discord](https://discord.com/channels/830127596355190804/1196503124249157702/1196921441086603304). 

I then removed the wallet from my profile so I could re-add it. Once it was re-added the updates appear to have fixed themselves, however I noticed that despite my uptime I was queued for rewards, and found that the node operator page UI was displaying duplicates of my node's info, [reported here](https://discord.com/channels/830127596355190804/1196503124249157702/1196925570085290054). A bit later another a community member saw the conversation and asked me if i also received duplicate cNFTs, and it [turns out I did](https://discord.com/channels/830127596355190804/1196503124249157702/1197022802482561054).

Node in question: CBMy84Sdd5XgLJwTxf89h2W4E2fAJGw87cDCoTXCkEn1

Even though this node appears to have never made it into the top 150 nodes at any point according to the system, at the time of this issue submission the UI still shows duplicate boxes and current status shows "ONLINE & QUEUED FOR REWARDS," but to add to the mystery I also see 1.04064362 of $SHDW accrued, which is unexpected if the node has been queued the whole time:
![Screenshot 2024-01-17 at 2 25 33 AM](https://github.com/GenesysGo/dagger-testnet-issues/assets/11333794/4755ac13-6dd7-444b-bff2-b3113b4c7e55).

**Desktop (please complete the following information):**
 - OS: Sonoma 14.1.2
 - Browser: Brave
 - Version: v1.61.116

**Comment by tracy-codes** [comment]
This has been resolved
