### ISSUE TITLE
The node was working normally, but after about half a day a "timeout syncing with peer" error occurred (v0.8.0)

### ISSUE THREAD

**Issue by fetith** [GenesysGo/dagger-testnet-issues#30]

**Comment by fetith** [comment]
As additional information, after the above, 
only the following logs "metrics - datapoint" and "metrics - run: submit status: 204" are output.

[INFO] dagger_logger::metrics - datapoint: uptime_metrics node_id="AjfGwVoEgwdirE6LC86CW58tX9NJdfUSmBkHB4DyEghN" is_up=true start_ts=1705489851262 current_uptime_ms=14951916 uptime_added_ms=5000 last_successful_sync_ts=1705504807172
[INFO] dagger_logger::metrics - datapoint: uptime_metrics node_id="AjfGwVoEgwdirE6LC86CW58tX9NJdfUSmBkHB4DyEghN" is_up=true start_ts=1705489851262 current_uptime_ms=14956916 uptime_added_ms=5000 last_successful_sync_ts=1705504812211
[WARN] dagger_logger::metrics - run: submit status: 204

**Comment by fetith** [comment]
When I received the message below and restarted, the finalized log started to be output.
I will continue to check to see if it happens again.
<img width="619" alt="image" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/67474560/9d9e1698-d48f-4234-8b63-83786bcec8d2">

**Comment by fetith** [comment]
It was working fine until a few hours ago, but sfter outputting several timeouts, now only "dagger_logger::metrics" is output.
Provides the latest logs.
[config.zip](https://github.com/GenesysGo/dagger-testnet-issues/files/13997606/config.zip)

**Comment by dteh** [comment]
I have the same issue, interestingly the timeouts are logged at the same time too. Are the remote peers stable? Who are you using to host the server? I am using Contago.

Also seems like dagger limits the number of retries on timeout before just giving up completely
