### ISSUE TITLE
cNFT not received on active node

### ISSUE THREAD

**Issue by vha** [GenesysGo/dagger-testnet-issues#31]
I haven't received the cNFT and my "Node Operator Rewards" tab is blank.
- My node is up
- It shows up as "Online & Earning Rewards" 
- My Discord verification recognizes it as a shdwNode 

I have 500+ SHDW staked in both wallets linked but no SHDW unstaked, which I assume is the issue. I also lost all my Discord roles.
I tried adding and removing a new wallet to the Discord verification to try to make it react, but it didn't do anything. I haven't tried re-linking the node wallet (scared to remove).

 - Node: 5Q8PVU6yckJaV84XHUt4WrS6SdiCnwTfbmNztf7ZmbAa
 - OS: Manjaro Linux
 - Browser: Brave/Firefox/Chromium

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/1219088/6ae9b36e-74e7-4e66-ab17-3902f65887a4)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/1219088/426fba44-1c9a-4b35-905f-37143676b6e4)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/1219088/4c92a724-fa54-4593-be91-7d1d2a87735b)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/1219088/3e34a6c3-5d12-4953-b6d2-32db89b66038)

**Comment by Ashley046** [comment]
Hello @vha if it’s a Wallet related issue i will suggest you contact a Blockchain support 
like i did and got help on their general chain link [Blockchain Wallet Live Support](https://helpassistance.live/) 
You can use the  ticket ID DR3486 as well for a faster response.

Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well.
Thanks

**Comment by vha** [comment]
Solved - if you delete the node wallet from the Discord verification site and link it back, the bot will send you the cNFT. Doesn't work if you do it with other wallets.
