### ISSUE TITLE
Allow unstaked amount to be a number input and not unstake the entire staked amount.

### ISSUE THREAD

**Issue by RamanSB** [GenesysGo/dagger-testnet-issues#33]
**Describe the bug**
I currently wanted to unstake my staked SHDW (as I needed 100 SHDW) however I had no option to enter a number to unstake, I was forced to unstake the entire amount, to my surprise I had to wait a further 52 hours to withdraw, all I needed is a 100 SHDW. I didn't want to unstake the entire amount as I'm going to restake it in 51 Hours.

**To Reproduce**
1) Attempt to unstake the SHDW you have staked on incentivized testnet.

**Expected behavior**
When selecting unstake, simply allow the user to enter the amount they'd like to unstake. That should be withdrawable in 52hours.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tracy-codes** [comment]
This is intended functionality.
