### ISSUE TITLE
Top 150 from launch until January 18th, 0.835 SHDW rewards

### ISSUE THREAD

**Issue by rhizanthemum** [GenesysGo/dagger-testnet-issues#36]
**Describe the bug**
I was in the top 150, earning rewards the entire time from launch until the bug was found on 1/18 or 1/19 - which should have rewarded me 40-60 SHDW, but I only see 0.835.

I'm missing some finalized from the total but that was during the downtime.

```
dagger@dagger:~$ more config.log | grep finalized | wc -l
918809
```

Furthermore, the node operator page only shows me having 55 minutes of uptime.

<img width="536" alt="image" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/128459463/584fc59e-1f14-491e-a26b-f627619aa4b4">

I was clearly in the top 150 the entire first two days until the arbitrary restart issue.

It even said I had earned 300 SHDW.

**Expected behavior**
I expected to be rewarded 0.9 SHDW per hour from launch until I was kicked out of the top 150.

**Desktop (please complete the following information):**
 - OS: Ubuntu latest stable

Node ID: AH1DNeVxFE8BmrF1fGxrh3TX3MgSMfZzTtbt1gkaUKnS

**Comment by tracy-codes** [comment]
Please join the discord and read the announcements, it contains context that answers your questions and concerns here.

**Comment by rhizanthemum** [comment]
hell yhea 0.835
