### ISSUE TITLE
Migrating to new Node shows wrong (old) CPU, RAM, & Storage

### ISSUE THREAD

**Issue by NateTheGreatX** [GenesysGo/dagger-testnet-issues#37]
**Describe the bug**
Minor bug on CPU,RAM, & Storage reporting.  I migrated from my AMD Ryzen 4800u to a Ryzen 6900HX.  

**To Reproduce**
1. scp id.json and other `/home/dagger` contents to new node
2. installed dagger using wield-installer.sh
3. ran new node
4. checked node dashboard with public key

**Expected behavior**
Expected to see same public key with new cpu information & disk space.  If the reported diskspace is wrong is the dashboard giving proper data?

JSON from dashboard:
```
 {
        "node_id": "8d2EFhvSkMHAdR3iULxK5AsLoT6RRJYqQZ8WXkw27gdk",
        "cpu": 16,
        "ram": 65261744,
        "storage": 1900288966,
        "cpu_type": "AMD Ryzen 7 4800U with Radeon Graphics",
        "last_updated": "2024-01-18T17:04:54.118Z",
        "wield_version": "0.8.0",
        "lat": 0,
        "lon": 0,
        "ip_addr": ""
    }
```
[node-dagger-node-log-grep.txt](https://github.com/GenesysGo/dagger-testnet-issues/files/14105716/node-dagger-node-log-grep.txt)

**Comment by ksang77** [comment]
i upgraded the RAM from 16gb to 32gb, restarted the computer and node is up for a day already, but dashboard still showing old spec. how to refresh? please help

**Comment by NateTheGreatX** [comment]
after the 0.8.1 upgrade this seems to have updated the reported cpu & storage.

**Comment by ksang77** [comment]
> after the 0.8.1 upgrade this seems to have updated the reported cpu & storage.

yes it did

**Comment by pgghub** [comment]
I reinstall ubuntu and added more storage to my system using LVM method. However the dashboard still shows the old values

node ID = DRgbNKierbTdhNGi1LfusfYoAJes4TsfH7e8cy73yTDB

OLD Storage = 824646524
NEW Storage = >2TBs

Is there command I can run on the wield node to update the system specs? I am assuming specs might increase overtime, but  not sure how to push the new specs to the network.

**Comment by franzer** [comment]
Right now only new hardware is picked up on version changes, however this doesn't change anything regarding earning rewards.  We will keep it this way for the rest of the testnet, but we may look to change it in the future.  Appreciate the heads up though.
