### ISSUE TITLE
Dagger Node Keeps Freezing Every 4-6 hours on 2 Seperate VPS and requires Stop and Start to get it back running

### ISSUE THREAD

**Issue by HB50007** [GenesysGo/dagger-testnet-issues#4]
I am currently running 2 nodes. 1 on Google Cloud VPS and 1 on CONTABO VPS. The issue that i noted that both my nodes will run for 4-6 hours each time before they no longer finalized. And i would have to do a manual stop and start and they will be back on again. You can see from the CPU chart the period that they are up and running and period that they are not which require a manual stop start.

**#Node 1**
Node 1 Pub ID: Hp6bdWqcFNKqYVAfJt59ktMuVteCttFSqyRuu2KhCSDy
This node is running on Google Cloud Series E2, 16vCPU + 32GB, 250GB SSD Persistent disk.

Node 1 has been running for around 2 days. I ran this cmd to extract some logs: "tail -n 5000000  config.log > ~/GCP_LOGS.txt"

Here is the link to download the logs: https://we.tl/t-Y2uKrhg7XU

I have also attached the GPU Chart for this node.
<img width="904" alt="AWS_VPS_CPU_CHART" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/148735732/0457a267-be46-4e32-87bc-02735fa004ba">

**#Node 2**
Node 2 Pub ID: n7rPKpu14FRGFfwFLssyg9UVkpud3twy22mW7YMypTh
This node is running on Contabo, 24vCPU + 120GB, 2.4 TB SSD

Node 1 has been running for around 1 day. I ran this cmd to extract some logs: "tail -n 2000000  config.log > ~/CONTABO_LOGS.txt"

Here is the link to download the logs: https://we.tl/t-pxCO2GlPVY

<img width="935" alt="Contabo_VPS_CPU_Chart" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/148735732/f2d64b15-e5fd-4a9d-8b20-fddc13a0f05a">

**Comment by HB50007** [comment]
<img width="944" alt="AWS_DROP_GRAPH" src="https://github.com/GenesysGo/dagger-testnet-issues/assets/148735732/836e1db0-357f-4657-9a91-0e519212ceba">


#Node 3
Node 3 Pub ID: F3gm2fudUdkGDNwMF8rNbyvMMZ3ozjwCjR2BdJw1684o
This node is running on AWS EC2 (Instance type c5.4xlarge), 16vCPU + 32GB, 250 GB SSD

Node 1 has been running for around 1 days. I ran this cmd to extract some logs: "tail -n 5000000  config.log > ~/AWS_LOGS.txt"

Here is the link to download the logs: https://we.tl/t-7ljBdETOgo

**Comment by HB50007** [comment]
![Uploading AWS_DROP_GRAPH.png…]()

#Node 3
Node 3 Pub ID: F3gm2fudUdkGDNwMF8rNbyvMMZ3ozjwCjR2BdJw1684o
This node is running on AWS EC2 (Instance type c5.4xlarge), 16vCPU + 32GB, 250 GB SSD

Node 1 has been running for around 1 days. I ran this cmd to extract some logs: "tail -n 5000000  config.log > ~/AWS_LOGS.txt"

Here is the link to download the logs: https://we.tl/t-7ljBdETOgo

**Comment by tracy-codes** [comment]
Looks like issues #6, #10, #12, and #13 are related to this. Since this is the original report, we will communicate via this one.

**Comment by tracy-codes** [comment]
We hoped the recent 0.7.2 update would've resolved this issue, but it seems to be an issue with the epoch boundary process. The team is analyzing all the logs provided to see if the issue can be pinpointed.

**Comment by dansg1** [comment]
May have just had this happen for the first time. 
Contabo 16c VPS. My 24c is still running fine.
Looking at the logs it was finalizing fine and then just stopped at 20:53 and the logging stopped.
Restarted at 21:13.

Logs 
https://drive.google.com/file/d/1-EP76Xit9OktcOPfdnyJb_4GaBmn9_5v/view?usp=sharing

Grafana Dashboard if it's useful.
http://81.0.247.94:3000/d/rYdddlPWk/node-exporter-full?orgId=1&from=now-3h&to=now&refresh=10s

**Comment by tracy-codes** [comment]
We believe there's some issues related to the contabo hosting provider. While cost-effective, they seem to have some reliability issues. I'd suggest reaching out to your host provider for more support on your node's connectivity issues.
