### ISSUE TITLE
Duplicate logs, filled drive

### ISSUE THREAD

**Issue by cr1sp4rm1n** [GenesysGo/dagger-testnet-issues#43]
**Describe the bug**
Duplicate logs being created at /var/log/syslog and filled OS drive. Mine was over 225g and shut me down with full drive. 

**To Reproduce**
`tail /var/log/syslog` will show the same as 
`tail ~/config.log`

**Expected behavior**

**Screenshots**
![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/158636256/b22569ed-debe-4b72-80ff-c688e8383681)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/158636256/f90735b8-75ea-4c0f-833c-4c9c199b0b6b)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/158636256/a2aecfdd-e513-402c-9172-b7d8c64688a2)

**Comment by taylorabbey** [comment]
It is recommended that you verify proper syslog log rotation as well, as outlined in the docs section on configuring logrotate: https://docs.shdwdrive.com/operate/install
