### ISSUE TITLE
Testnet went down on 02/02

### ISSUE THREAD

**Issue by Aeonia123** [GenesysGo/dagger-testnet-issues#44]
**Node operators, please add your logs below**

**Describe the bug**
Testnet crash.

There were an unusual number of timeout syncing with peer errors for a few mins, then we started getting a mix of is_up=false and is_up=true, which after a while became all false.

Restart scripts restarted the node several times throughout. I copied and truncated the log due to limitations with the restart script. Continued with a small gap in the second log.

[config.0202.log](https://github.com/GenesysGo/dagger-testnet-issues/files/14152524/config.0202.log)

[config.0202.2.log](https://github.com/GenesysGo/dagger-testnet-issues/files/14152542/config.0202.2.log)

**Comment by Aeonia123** [comment]
Node id: FGrFgetn4Kyaz8Q53pdC8Y9w17iGzKDAWXVhJVUohecK
Provider: Contabo
Location: Germany

**Comment by dansg1** [comment]
Node ID: 4FBctMBZxw8bBDLsczihh6hbnKxN7vgG5zpZc2SaSKwc
Contabo UK

Log starts about 1 hour before the outage.

https://drive.google.com/file/d/1-VuP0_G5ULXwfjk5DaNGMFcZRX5Myfna/view?usp=sharing

**Comment by CleanPutter** [comment]
Node ID: F43E1SCnDfNc22eYnJcvbthzQtmvC9boYtCKDFg8P2SG
Location Canada

[feb2 log](https://github.com/GenesysGo/dagger-testnet-issues/files/14169256/feb2.log)

**Comment by tracy-codes** [comment]
The testnet is back up. We will reopen this issue if it halts due to similar behavior.
