### ISSUE TITLE
Node verified and UP but status N/A 

### ISSUE THREAD

**Issue by Mamorucha** [GenesysGo/dagger-testnet-issues#51]
I have my node up but showing my status N/A even i got shadows in my wallet
![Screenshot from 2024-02-09 01-26-23](https://github.com/GenesysGo/dagger-testnet-issues/assets/159493976/d7b5196b-7373-492a-a6d9-8f3e676bea2a)

**Comment by tracy-codes** [comment]
Please provide the full node address here in text. We can't copy the node address from a screenshot. Along with that, how many nodes are connected to your discord user?

**Comment by Mamorucha** [comment]
This is my first node id but i lost my access to it. Becuase i formatted my ubuntu and lost my priv key. Also how can i get my priv key from support to get access to this account?
GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL

This is the second one which i created and now is up
BUzcDRgs6Hvki7CA24E73yVhEzMepNEMpwRQtWv9Md3b

**Comment by Mamorucha** [comment]
> Please provide the full node address here in text. We can't copy the node address from a screenshot. Along with that, how many nodes are connected to your discord user?

This is my first node id but i lost my access to it. Becuase i formatted my ubuntu and lost my priv key. Also how can i get my priv key from support to get access to this account?
GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL

This is the second one which i created and now is up
BUzcDRgs6Hvki7CA24E73yVhEzMepNEMpwRQtWv9Md3b

**Comment by tracy-codes** [comment]
You will need to remove `GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL` from your discord user through the verification system if you've added it, previously.

As for your private key, nobody can recover it for you. That defeats the purpose of a secure private key. You are solely responsible for keeping track of your keys.

**Comment by Mamorucha** [comment]
> You will need to remove `GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL` from your discord user through the verification system if you've added it, previously.
> 
> As for your private key, nobody can recover it for you. That defeats the purpose of a secure private key. You are solely responsible for keeping track of your keys.

The problem is yesterday i had one node up but having the same issue. Do you have any comment for this?

**Comment by tracy-codes** [comment]
> > You will need to remove `GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL` from your discord user through the verification system if you've added it, previously.
> > As for your private key, nobody can recover it for you. That defeats the purpose of a secure private key. You are solely responsible for keeping track of your keys.
> 
> The problem is yesterday i had one node is but having the same issue. Do you have any comment for this?

What time in UTC was this at, yesterday?

**Comment by Mamorucha** [comment]
> > > You will need to remove `GLmFf23GA9jU6NJacm3Yb3b7rRdekTcQ2aDvQ4tetniL` from your discord user through the verification system if you've added it, previously.
> > > As for your private key, nobody can recover it for you. That defeats the purpose of a secure private key. You are solely responsible for keeping track of your keys.
> > 
> > 
> > The problem is yesterday i had one node is but having the same issue. Do you have any comment for this?
> 
> What time in UTC was this at, yesterday?

It was around 20:00. Check this one. 
![SAVE_20240209_015542](https://github.com/GenesysGo/dagger-testnet-issues/assets/159493976/7b9bc44a-cc1c-4ddf-bf00-5246dfefadb2)

**Comment by tracy-codes** [comment]
It looks like both of these have been removed from the discord verification system. Please try re-adding one of them to the verification system.

Additionally, if you are mamorucha in the Discord server, then the only wallet associated with your user is not a shdw node.

Not sure we can provide any further assistance here. Please try messaging in `#general-tech-support` in the Discord server and community members may be able to further assist you with this issue, as everything within the network seems to be operating as expected so this isn't a technical issue with dagger.
