### ISSUE TITLE
Rewards and actually claimed rewards values discrepancy.

### ISSUE THREAD

**Issue by yoss4r1an** [GenesysGo/dagger-testnet-issues#52]
**Describe the bug**
"Claim Rewards" in staking protocol show 0.261251874 SHDW available to claim which is less than I saw couple days ago ~1.0.
When "Claim rewards" pressed shows 1.088114 SHDW to claim.

**To Reproduce**
1. Go to 'testnet.shdwdrive.com'
2. Click on 'Claim Rewards'
3. Click on button 'CLAIM REWARDS'
4. See values discrepancy between point 2 and 3.

**Expected behavior**
I would expect values from 'Claim Rewards' and when actually claiming rewards to be equal.

**Screenshots**
![1](https://github.com/GenesysGo/dagger-testnet-issues/assets/66412609/ebc56810-6b3d-48ec-876b-dcbe247525aa)
![2](https://github.com/GenesysGo/dagger-testnet-issues/assets/66412609/508cf1dc-c3a5-4626-aea7-c6b6dc779864)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Brave
 - v1.62.162 (Feb 7, 2024)

**Smartphone (please complete the following information):**
 - Device: OnePlus 8 Pro
 - OS: Android OxygenOS 13.1
 - Brave
 - v1,62,156

**Additional context**
my wallet address: xxx

I have now claimed rewards.

edit: After claiming rewards website still shows the same value "Available to claim" (~0.26) except now with the time limit on.

**Comment by tracy-codes** [comment]
Thank you for this report! We will investigate.

**Comment by tracy-codes** [comment]
hi! This should now be resolved. If there's still a discrepancy in the UI vs when you claim, the claim value in the wallet simulation is correct and the UI will self-correct after your next claim transaction is processed.
