### ISSUE TITLE
Re-Installing Ubuntu and node shows the OLD node SPECs (Wrong Storage Value)

### ISSUE THREAD

**Issue by pgghub** [GenesysGo/dagger-testnet-issues#54]
**Describe the bug**
After upgrading the node HW the specs reported in the dashboard show the old value for the storage size. I upgraded the harddrives on the system + Reinstall ubuntu + reinstall the node

**To Reproduce**
Steps to reproduce the behavior: **(Using a metal server not a VSP)**
1. Upgrade physical hard drives on the server
2. Re-install Ubuntu on small SDD drive (240GB) using LVM partition
3. Boot Ubuntu
4. Partition and NVMe drive size 2TBs and set it up for LVM management
5. Ubuntu shows the the filesystem with both drives extended to 1 LV size, total storage for root => 2TBs (A little greater than 2TBs ---- 240GB + 2TBs)
6. Install wield node using the automated scrip
7. Replace the old id.json file
8. Finish installation using the automated script
9. Verify the node is finalizing 
10. Check dashboard for specs and it shows the old value ~ 840GBs not +2TB

Keep in mind that all other specs RAM and CPU stayed the same

**Expected behavior**
Expected to see same public key with new disk space information

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/20260733/aa69731b-b9fc-4861-af9b-ed36061d5c89)

![image](https://github.com/GenesysGo/dagger-testnet-issues/assets/20260733/f684791f-c50b-43f5-bd1b-2b948e7fda92)

**Comment by franzer** [comment]
Thanks, we will look into this - More important is that your node is up and running and participating in testnet, which it sounds like it is.

**Comment by pgghub** [comment]
Thank you 😊

**Comment by pgghub** [comment]
Hello @franzer , just checking to see if you found anything on your end. Or if there is anything I can get from my node that might help :) 

Thanks

**Comment by pgghub** [comment]
This issue was fixed when the new 0.8.4 upgrade was released. However, when doing the upgrade, it failed, and required me to re install the node. So I am not sure if the upgrade fixed me issue, or the re installation of the node did the job. I always use the automated script just FYI.
