### ISSUE TITLE
Security vuln reported

### ISSUE THREAD

**Issue by torroh333** [GenesysGo/dagger-testnet-issues#58]
This is a security vulnerability and has been redacted. Please report using the security vulnerability report feature instead of creating a public issue.

**Comment by tracy-codes** [comment]
Hello, please report this as a security vulnerability. Reporting in this manner breaks our policy for reporting security issues and we reserve the right to remove this public issue until it's resolved.

**Comment by torroh333** [comment]
Apologies for not recognizing it as a network vulnerability! I have now submitted it as a security issue.
