### ISSUE TITLE
Dagger node not doing anything for 5+ hours (nothing in config.log file) - Full log file attached.

### ISSUE THREAD

**Issue by rsamban** [GenesysGo/dagger-testnet-issues#7]
**Describe the bug**
Dagger node not doing anything for 5+ hours (nothing in config.log file)

er { pubkey: Hv6gUUxDKF4u2ik5AsgbR9dAkURopQCueKMv4K7dKf24, addr: 185.163.117.87:2030 }, Peer { pubkey: J3bs7axA7XtcwBiuDpskkPpFcHHnKC6XW3DHHbNcGXzK, addr: 158.220.123.196:2030 }, Peer { pubkey: J8BPuouEo8wtehNXdYrMTBSJn5Z3pJZ2LKNwwmvGmRFi, addr: 144.91.100.91:2030 }}
2024-01-04T22:00:21.449647718+00:00 [INFO] dagger::controller - entering controller loop
2024-01-04T22:00:21.450003364+00:00 [INFO] dagger::client - entering conn loop
2024-01-04T22:00:21.450088503+00:00 [INFO] dagger::client - entering sync loop
2024-01-04T22:00:21.450153807+00:00 [INFO] dagger::processor - entering processor loop
[config.log.tgz](https://github.com/GenesysGo/dagger-testnet-issues/files/13837635/config.log.tgz)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by eviipx** [comment]
Had same issue twice yesterday, both times it solved it self after 2x reboots. (also tried to only restart the wield service a few times, but did not help). Today I got a mail from my VPS provider telling me they had resolved some issues they had with my server. So could have been som HW / infrastructure issue the VPS provider had that caused the issue for me.

**Comment by rsamban** [comment]
I rebooted my VPS and that issue us gone. However, I am getting timeout issue.
I have attached the log file.

Also, I have upgraded the node to 0.7.2 and restarted it.
[config.log_20240105.tgz](https://github.com/GenesysGo/dagger-testnet-issues/files/13848119/config.log_20240105.tgz)

**Comment by rsamban** [comment]
After reboot and ugrading o 0.7.2, my node seems to be running with no issues for past ~ 20 hours, thank you
