### ISSUE TITLE
failed connect Unspecified after changing Pubkey

### ISSUE THREAD

**Issue by wisdomtrader** [GenesysGo/dagger-testnet-issues#8]
On 1/4, I changed my pubkey and followed the steps
1.  stop wield service
2.  change pubkey
3. started wield service

After around 10 minutes, my node finally joined and I was getting finalized messages
After hours, I went back to check my node and now my node is getting these spam messages I have attached in the logs
Spoke with the Devs and they recommended that I upload my config.log file, which I have attached to this case.

  [https://drive.google.com/file/d/1ahBDgQSyEgDZSWe1LOQXh57goMN2XCcY/view?usp=drive_link](url)

**Comment by tracy-codes** [comment]
This issue is resolved as of a recent version upgrade.
